format = """
$conda\
$username\
$hostname\
$localip\
$directory\
$git_branch\
$git_commit\
$git_state\
$git_metrics\
$git_status\
$container\
$gcloud\
"""

[conda]
symbol = ''
format = '[$symbol\($environment\)  ](dimmed)'
ignore_base = false

[directory]
truncation_length = 1
truncation_symbol = '…/'

[character]
success_symbol = '[➜](dimmed green) '
error_symbol = '[➜](dimmed red) '
