# Get editor completions based on the config schema
"$schema" = 'https://starship.rs/config-schema.json'

# Inserts a blank line between shell prompts
add_newline = false

[character]
disabled = true

[cmd_duration]
disabled = true

[battery]
disabled = true

[lua]
disabled = true

[nodejs]
disabled = true
